# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: SonarSource.sonarcloud.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: AzureDevOps
    organization: 'amelfraisse-github'
    scannerMode: Other
    
- task: Maven@2
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'
    codeCoverageToolOption: Cobertura
    sonarQubeRunAnalysis: true
    
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/ucomp_twitter_basic_retriever/**/site/cobertura/coverage.xml'
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/ucomp_twitter_basic_retriever/**/site/cobertura/coverage.xml'
    
- task: SonarSource.sonarcloud.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

