# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Run SonarCloud analyse
      run: mvn --batch-mode clean package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=amelfraisse-github -Dsonar.projectKey=amelfraisse_ucomp_twitter_basic_retriever
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

 #   - name: SonarCloud Scan
 #     uses: sonarsource/sonarcloud-github-action@master
 #     env:
 #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  

 #   - name: Publish to GitHub Packages Apache Maven
 #     run: mvn deploy
 #     env:
 #       GITHUB_TOKEN: ${{ github.token }}
